name: "limnobotics"
description: "Robotics meets Limnology"

url: "http://localhost:4000"


# change this if the root directory is not the root of the server
baseurl: ""

# markdown specifications
markdown: kramdown
#kramdown:
#  input: GFM
permalink: pretty

# custom menu setup
menu:
  - text: 
      en: Home
      fr: Accueil
      de: Startseite
    url: /
  - text: 
      en: Planktothrix
      fr: Planktothrix
      de: Planktothrix
    url: /planktothrix/
  - text: 
       en: Publications
       fr: Publications
       de: Publikationen
    url: /publications/
  - text:
       en: People
       fr: L'équipe
       de: Das Team
    url: /people/
  - text: 
       en: Gallery 
       fr: Gallerie 
       de: Gallerie 
    url: /media/
#  - text: Something
#    url: /something/
#    subitems:
#      - text: something else 
#        url: /something/else/
#
main_language: en
languages:
  - id: en
    name: English
  - id: de
    name: Deutsch
  - id: fr
    name: Français




